### ISSUE TITLE
problem with Select an Identifier Mapping Database on PathVision 

### ISSUE THREAD

**Issue by tamlav** [PathVisio/pathvisio.github.io#10]
I install PathVision on my window computer.
I am following this: https://pathvisio.org/tutorials/getting-started.html

I Installed the WikiPathways plugin but when trying to 'select gene Database' I got an error: Failed to open gene database; could not connect to database.

I download Hs_Derby_Ensembl_105.bridge from https://bridgedb.github.io/data/gene_database/

I could not find any help on this issue.

Thanks,

**Comment by oddlyaware** [comment]
I think we have the same question. I was following [the tutorial ](http://academy.wikipathways.org/stages/draw-geneproduct/index.html) but couldn't find GeneProduct ACO2. I downloaded only the homo sapiens from the file you mentioned, loaded it via Data > Select Gene Database (note that the [PathVisio Book tutorial](https://pathvisio.org/pathvisio-book/load-identifier-mapping-database.html) here is outdated as there is no "Load Identifier Mapping" option under "Files"... & still cannot find my GeneProduct.

Pity. The tutorial was going so swimmingly, but stumped at the first practice.

**Comment by mkutmon** [comment]
My apologies! This issue somehow skipped my inbox :(. 
There were some issues with the identifier mapping database version 105 which should be resolved now. Please let me know if this error still occurs!

**Comment by mkutmon** [comment]
@oddlyaware the PathVisio Book is only for PathVisio 4 which is not yet fully released but in a testing phase.
