### ISSUE TITLE
Whats-New-GPML2021.html Updates Authors

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio.github.io#5]
Regarding the documentation below:
- [x]  why is the email address an attribute?
- [x] where/how is the order of authors stored?
- [x] will it be possible to add authors who do not have a WP account?
- [x] Should the Xref (e.g. Orcid) be added as a URL, or with Database name annotation?

![image](https://user-images.githubusercontent.com/26277832/121404727-81fdcc00-c95c-11eb-8a98-bdebafa58532.png)

**Comment by DeniseSl22** [comment]
Regarding email, see also:
![image](https://user-images.githubusercontent.com/26277832/121406688-bd00ff00-c95e-11eb-934f-8f22a89e8df0.png)

**Comment by Finterly** [comment]
Hi. Sorry the code example for Author was incorrect, I have updated it now. 
![image](https://user-images.githubusercontent.com/28988687/121407541-b6bf5280-c95f-11eb-855f-310b39c42ddb.png)

**Comment by mkutmon** [comment]
Xref is always with identifier and database which can be converted be converted to URLs.

**Comment by DeniseSl22** [comment]
> Xref is always with identifier and database which can be converted be converted to URLs. But we will stick with the official identifier system here as for all other databases for consistency.

Yes agreed! So we should add Orcid then as a Datasource for BridgeDb; or are these loaded from somewhere else (or hardcoded within PV)? It's not the type of Database which is normally a part of BridgeDb (same as pubmed, DOI, etc.)....

**Comment by Finterly** [comment]
We have added Orcid as a Datasource for BridgeDb. There are a number of Datasources to be added. We are also adding a Prefix column to BridgeDb. I am still looking over these [here](https://docs.google.com/spreadsheets/d/1fV0V6Evflhhh28ChA6MJGebsgZoguyCouTey6jbTO8I/edit#gid=0). There are also a number of Datasources in BridgeDB not yet on identifiers.org that we would like added to identifiers.org.

**Comment by mkutmon** [comment]
@DeniseSl22 as mentioned by Finterly, the datasources.tsv has all of those databases in it already. so bridgedb can deal with these :)
